### ISSUE TITLE
Assertion failed - bug.

### ISSUE THREAD

**Issue by Rajlo350** [roblox-ts/roblox-ts#1603]
Hey, I got this error when trying to compile my code. Not too sure what could've caused this since it was so sudden. Any clue?

_This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues_

```
Error: Assertion Failed!

at Object.assert (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformIdentifier (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformIdentifier.js:105:14)
    at Object.transformExpression (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
    at Object.transformWritableExpression (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\transformWritable.js:36:51)
    at transformForInitializer (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:83:48)
    at C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:94:38
    at C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:29:28
    at transformForOfStatement (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:338:45)
    at Object.transformStatement (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformStatement.js:76:16)
    at C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:15:100
(node:16812) UnhandledPromiseRejectionWarning: Error: Assertion Failed! 
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at Object.assert (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformIdentifier (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformIdentifier.js:105:14)
    at Object.transformExpression (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
    at Object.transformWritableExpression (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\transformWritable.js:36:51)
    at transformForInitializer (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:83:48)
    at C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:94:38
    at C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:29:28
    at transformForOfStatement (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:338:45)
    at Object.transformStatement (C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformStatement.js:76:16)
    at C:\Users\Rajlo\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:15:100
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:16812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Dionysusnu** [comment]
First of all, basic info.
Please add the following command outputs:
`rbxtsc -v`
`npm ls roblox-ts`
`npm ls typescript`
Do you know when the failure started happening? Can you identify the piece of code that causes the failure?

**Comment by Dionysusnu** [comment]
To get quicker help, consider joining the discord: https://discord.gg/f6Rn6RY

**Comment by Rajlo350** [comment]
The error was caused because of a comment that disabled the debugger, forcing it to compile invalid code. Not an actual bug, solved.
