### ISSUE TITLE
non-JsxChild JsxExpression inside JsxFragments cause assertion failed.

### ISSUE THREAD

**Issue by daniel-melanson** [roblox-ts/roblox-ts#1769]
[Playground.](https://roblox-ts.com/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKBaqsRwgDcBTOGABZ8A3nnwBfOMgB2AEzjB4qHGGAAbHhSao1yChTgBZAJ4BhFRGk9p8HuWuyDSOgDpz4S9fjCmASDAArsRqwKhwUA48UAAUAJQAXByuAKIaIF5wAD5wAXI8GMBW8j6+vhEwAVDScNF+pQA8WMjpAHx1DW2lXcIAjOLtvvVUnQ1UTa11scy+-eJAA)

Inside a regular `JsxChild`,
```tsx
<frame>
  {""}
</frame>
```
We receive an error:
```
error TS2322: Type 'string' is not assignable to type 'JsxNode'.
```

However, pop that illegal `JsxExpression` into a fragment and
```tsx
<>
  {""}
</>
```
And we fail an assertion. Same behavior if the `JsxExpression` encloses a number or function. [Booleans will compile.](https://roblox-ts.com/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKCdQgDsL5k4BeOAN4BfZkypVEOCADcApnBgALeQLz4hcZOwAmcYPDbhgAG1kVWx5BQpwAsgE8AwjkjtZ7eLPLvtNpHQA6Z3AOd3gBJgBIMABXYmNgVDgoH1koAAoASgAuSUCAUVMQMLgAHzgYnVkMYDddCMjIlJgYqHY4dKjGgB4APi7GgRgoGNkhAe6qfsbM5kjxoSA) But the emitted code does not do anything with it.

[If the value inside the `JsxExpression` is an regular object (or instance of a class)](https://roblox-ts.com/playground/#code/JYWwDg9gTgLgBAJQgQwMbwGZQiOAiAASgCMAPGAZwHps0Y8BuAKCdQgDsL5k4BeOAN4BfZkypVEOCADcApnBgALeQLz4hcZOwAmcYPDbhgAG1kVWx5BQpwAsgE8AwjkjtZ7eLPLvtNpHQA6Z3AOd3gBJgBIMABXYmNgVDgoH1koAAoASgAuSUCAUVMQMLgAHzgYnVkMYDddCMjIlJgYqHY4dKjGgB4APi7GgWQhAe6qfsbM5kiRoSA) then it will compile, and provide some checks to determine the type of the value.

I am new to Roact, and Jsx in general, so take my findings with a grain of salt. I am not trying to imply that the behavior of booleans and objects is incorrect, just documenting my findings.

**Comment by daniel-melanson** [comment]
I discovered this behavior, when I accidentally had a `{""}` inside one of my JsxFragments in `v1.2.7`, Code compiled find, but emitted something similar to:
```lua
for _k, _v in pairs(" ") do
 -- code
end
```

**Comment by Dionysusnu** [comment]
> I discovered this behavior when I accidentally had a `{""}` inside one of my JsxFragments in `v1.2.7`, Code compiled fine, but emitted something similar to:
> 
> ```lua
> for _k, _v in pairs(" ") do
>  -- code
> end
> ```

So this is a regression introduced in v1.2.8 or v1.2.9, am I getting that part right?

**Comment by Dionysusnu** [comment]
Regression introduced in #1666

**Comment by Dionysusnu** [comment]
The regression is actually the fixing of the previous issue, which would try to pass the string to `pairs`. But this then exposed the issue that strings were not covered in any other part of the code, causing an assertion failure.

**Comment by daniel-melanson** [comment]
Callstack:
```
Error: Assertion Failed! 
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/Shared/util/assert.js:7:15)
    at createJsxAddChild (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/jsx/transformJsxChildren.js:161:25)
    at transformJsxChildren (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/jsx/transformJsxChildren.js:236:38)
    at transformJsxFragment (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/expressions/transformJsxFragment.js:14:53)
    at transformExpression (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/expressions/transformExpression.js:97:16)
    at transformReturnStatementInner (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/statements/transformReturnStatement.js:17:68)
    at transformReturnStatement (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/statements/transformReturnStatement.js:47:40)
    at transformStatement (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/statements/transformStatement.js:76:16)
    at /home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/transformStatementList.js:15:123
    at /home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/classes/TransformState.js:108:60
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Assertion Failed! 
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/Shared/util/assert.js:7:15)
    at createJsxAddChild (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/jsx/transformJsxChildren.js:161:25)
    at transformJsxChildren (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/jsx/transformJsxChildren.js:236:38)
    at transformJsxFragment (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/expressions/transformJsxFragment.js:14:53)
    at transformExpression (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/expressions/transformExpression.js:97:16)
    at transformReturnStatementInner (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/statements/transformReturnStatement.js:17:68)
    at transformReturnStatement (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/statements/transformReturnStatement.js:47:40)
    at transformStatement (/home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/statements/transformStatement.js:76:16)
    at /home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/nodes/transformStatementList.js:15:123
    at /home/daniel/.nvm/versions/node/v17.3.1/lib/node_modules/roblox-ts/out/TSTransformer/classes/TransformState.js:108:60

Node.js v17.3.1
```

**Comment by daniel-melanson** [comment]
> The regression is actually the fixing of the previous issue, which would try to pass the string to `pairs`. But this then exposed the issue that strings were not covered in any other part of the code, causing an assertion failure.

Yes, correct, was about to comment something similar to this.
