### ISSUE TITLE
Assertion failed at transformJsxTagNameExpression when using custom jsxfactory.

### ISSUE THREAD

**Issue by vendkita** [roblox-ts/roblox-ts#1816]
# Problem
When trying to make something similar to Roact, I encountered a compiler bug that only happens with jsx declarations.
## Error
```
Error: Assertion Failed!
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformJsxTagNameExpression (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:18:33)
    at C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:36:55
    at C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:108:60
    at TransformState.capturePrereqs (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:103:9)
    at TransformState.capture (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:108:30)
    at transformJsxTagName (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:36:41)
    at transformJsx (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsx.js:22:84)
    at transformJsxSelfClosingElement (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformJsxSelfClosingElement.js:6:44)
    at transformExpression (C:\Users\user\AppData\Roaming\npm\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
```

## Reproduction
1. In a new folder do ``` rbxtsc init package ```
2. Accept all prompts
3. Delete everything under /src and /out
4. Set ``` "jsxFactory" ``` to ``` Luck.createElement ``` in tsconfig.json
5. Under /src add the following files:
### createElement.ts
```typescript
export function createElement<T extends keyof CreatableInstances = keyof CreatableInstances>(
	tag: T,
	attributes: { [key in keyof CreatableInstances[T]]?: CreatableInstances[T][key] },
	...children: Instance[]
) {
	const element = new Instance(tag);

	// append children
	children.forEach((child) => {
		child.Parent = element;
	});
	return element;
}
```
### index.d.ts
```typescript
import { createElement } from "./createElement";
declare namespace Luck {
	export { createElement };
}

declare global {
	namespace JSX {
		type IntrinsicElementsMap = {
			part: {
				[key in keyof Part]?: Part[key];
			};
		};
		interface IntrinsicElements extends IntrinsicElementsMap {}
	}
}
```
### test.tsx
```typescript
import { Luck } from "./index";
<part />;
```
6. run ```npm run build```

**Comment by Dionysusnu** [comment]
You should not use @ts-ignore, it causes compiler issues. It may well play a part in this one. If you can reproduce this without the ts-ignore, please post just the minimum files you need for that.

**Comment by vendkita** [comment]
> You should not use @ts-ignore, it causes compiler issues. It may well play a part in this one. If you can reproduce this without the ts-ignore, please post just the minimum files you need for that.

I removed that portion all together, but there is still the exact same error.
