### ISSUE TITLE
Error: Assertion Failed!

### ISSUE THREAD

**Issue by geometrical1** [roblox-ts/roblox-ts#2378]
i was on roblox-ts as usual. then i got this bug:
[3:43:06 PM] Starting compilation in watch mode...

\node-v18.3.0-win-x64\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:162
                throw e;
                ^

Error: Assertion Failed!
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (\node-v18.3.0-win-x64\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at createJsxAddChild (\node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:159:25)
    at transformJsxChildren (\node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxChildren.js:234:38)
    at transformJsx (tnode-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsx.js:31:53)
    at transformJsxElement (node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformJsxElement.js:6:44)
    at transformExpression (\node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
    at transformParenthesizedExpression (node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformParenthesizedExpression.js:11:70)
    at transformExpression (node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:97:16)
    at node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformVariableStatement.js:99:136
    at TransformState.capturePrereqs (node-v18.3.0-win-x64\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:127:9)

**Comment by geometrical1** [comment]
nvm. deserved error, did some wierd stuff with the jsx tree
