### ISSUE TITLE
Permission error w/ Rojo in watch mode

### ISSUE THREAD

**Issue by LouieK22** [roblox-ts/roblox-ts#256]
1. Start rbxtsc in watch mode
2. Start rojo in watch mode
3. Create a new folder
4. Create an index.ts inside the new folder
5. rbxtsc crashes with a permission error **or** some files fail to compile without any error output (similar to #255)

```
Change detected, compiling..
{ Error: EPERM: operation not permitted, stat 'C:\Users\louie\Documents\_Coding\Roblox\gun-game\out\client'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (C:\Users\louie\AppData\Roaming\nvm\v8.15.0\node_modules\roblox-ts\node_modules\graceful-fs\polyfills.js:295:24)
    at Compiler.<anonymous> (C:\Users\louie\AppData\Roaming\nvm\v8.15.0\node_modules\roblox-ts\out\Compiler.js:298:28)
    at Generator.next (<anonymous>)
    at C:\Users\louie\AppData\Roaming\nvm\v8.15.0\node_modules\roblox-ts\out\Compiler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\louie\AppData\Roaming\nvm\v8.15.0\node_modules\roblox-ts\out\Compiler.js:3:12)
    at Compiler.cleanDirRecursive (C:\Users\louie\AppData\Roaming\nvm\v8.15.0\node_modules\roblox-ts\out\Compiler.js:293:16)
    at Compiler.<anonymous> (C:\Users\louie\AppData\Roaming\nvm\v8.15.0\node_modules\roblox-ts\out\Compiler.js:381:24)
    at Generator.next (<anonymous>)
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\Users\\louie\\Documents\\_Coding\\Roblox\\gun-game\\out\\client' }
```

**Comment by Dog2puppy** [comment]
Are you using any sort of file syncing thing such as Google Drive?

**Comment by LouieK22** [comment]
Nope
