### ISSUE TITLE
Error: Assertion Failed! ForOf iteration type not implemented: <CLASS_NAME>

### ISSUE THREAD

**Issue by jisham318** [roblox-ts/roblox-ts#2586]
This is the console output:
```
Starting compiler..
Detected local install, using local install instead of global
[2:27:44 AM] Starting compilation in watch mode...

c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:169
                throw e;
                ^

Error: Assertion Failed! ForOf iteration type not implemented: VoxelFaces
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at getLoopBuilder (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:329:29)
    at transformForOfStatement (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:370:25)
    at transformStatement (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformStatement.js:76:16)
    at c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:27:123
    at c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:60
    at TransformState.capturePrereqs (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:128:9)
    at TransformState.capture (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:30)
    at transformStatementList (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:27:65)
    at transformForOfStatement (c:\Users\Jacob\source\repos\robot-rampage-ts\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:369:76)

Node.js v18.16.0
Compiler exited with code 1
```

And here is the code that seems to be causing the issue:
```ts
export class VoxelFaces {
	public Right: boolean = false;
	public Top: boolean = false;
	public Back: boolean = false;
	public Left: boolean = false;
	public Bottom: boolean = false;
	public Front: boolean = false;

	public constructor(
		right: boolean = false,
		top: boolean = false,
		back: boolean = false,
		left: boolean = false,
		bottom: boolean = false,
		front: boolean = false,
	) {
		this.Right = right;
		this.Top = top;
		this.Back = back;
		this.Left = left;
		this.Bottom = bottom;
		this.Front = front;
	}

	public static allTrue = new VoxelFaces(true, true, true, true, true, true);
	public static allFalse = new VoxelFaces(false, false, false, false, false, false);

	public get(faceName: string): boolean {
		return faceName === "Right"
			? this.Right
			: faceName === "Top"
			? this.Top
			: faceName === "Back"
			? this.Back
			: faceName === "Left"
			? this.Left
			: faceName === "Bottom"
			? this.Bottom
			: faceName === "Front"
			? this.Front
			: false;
	}

	public set(faceName: string, value: boolean): void {
		if (faceName === "Right") this.Right = value;
		else if (faceName === "Top") this.Top = value;
		else if (faceName === "Back") this.Back = value;
		else if (faceName === "Left") this.Left = value;
		else if (faceName === "Bottom") this.Bottom = value;
		else if (faceName === "Front") this.Front = value;
		else error("Invalid face name");
	}

	public copy(): VoxelFaces {
		return new VoxelFaces(this.Right, this.Top, this.Back, this.Left, this.Bottom, this.Front);
	}

	public *[Symbol.iterator](): IterableIterator<[string, boolean]> {
		const faceNames = ["Right", "Top", "Back", "Left", "Bottom", "Front"];
		for (const faceName of faceNames) {
			yield [faceName, this.get(faceName)];
		}
	}
}
```

It could very well be the fact that I don't really know TypeScript all that well and  I'm mostly relying on GitHub Co-Pilot's suggestions to learn the language.

**Comment by osyrisrblx** [comment]
Closing in favor of #1826
