### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by qurxtscoder** [roblox-ts/roblox-ts#2664]
Im getting this error every time I try to compile my code. Not sure if something is broken in my code or if it is a compiler issue.

Starting compiler..
Detected local install, using local install instead of global
[11:55:03 PM] Starting compilation in watch mode...

c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:169
                throw e;
                ^

Error: Assertion Failed! Destructuring not supported for type: any
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at getAccessorForBindingType (c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\util\binding\getAccessorForBindingType.js:139:25)
    at transformArrayBindingPattern (c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\nodes\binding\transformArrayBindingPattern.js:19:80)
    at c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformVariableStatement.js:125:153
    at TransformState.capturePrereqs (c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:128:9)
    at transformVariableDeclaration (c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformVariableStatement.js:125:68)
    at c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformVariableStatement.js:145:67
    at c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:60
    at TransformState.capturePrereqs (c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:128:9)
    at TransformState.capture (c:\Users\...\Documents\Github\QFramework2024\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:30)

Node.js v20.12.0
Compiler exited with code 1

**Comment by OverHash** [comment]
Your code will need some adjusting, since you are attempting to perform something essentially equivalent to
```ts
const item: any;
print(...item);
```
the compiler does not know how to handle this.

You'll need to find what file you are trying to do this and change this behavior. Using `git bisect` may be helpful to identify where the problem came from. If you only have a few files, it should be fairly trivial.

**Comment by qurxtscoder** [comment]
Ohh thanks I found the issue.
