### ISSUE TITLE
[ROACT/TSX] Compiler Bug: Assertion Failed!

### ISSUE THREAD

**Issue by doqedev** [roblox-ts/roblox-ts#2690]
(this is a template with Roact installed. @rbxts/react)

```json
"devDependencies": {
    "@rbxts/compiler-types": "^2.3.0-types.1",
    "@rbxts/types": "^1.0.775",
    "@typescript-eslint/eslint-plugin": "^7.8.0",
    "@typescript-eslint/parser": "^7.8.0",
    "eslint": "^9.2.0",
    "eslint-plugin-roblox-ts": "^0.0.36",
    "roblox-ts": "^2.3.0",
    "typescript": "^5.4.5"
  },
  "dependencies": {
    "@rbxts/cmdr": "^1.12.1",
    "@rbxts/react": "^0.3.6",
    "@rbxts/react-roblox": "^0.3.6",
    "@rbxts/services": "^1.5.4"
  }
```

# Actual Code
```tsx
import Roact, {StrictMode} from "@rbxts/react";
import { createPortal, createRoot } from "@rbxts/react-roblox";
import { Players } from "@rbxts/services";

const plr = Players.LocalPlayer
const gui = Players.LocalPlayer.WaitForChild("PlayerGui") as PlayerGui

const root = createRoot(new Instance("Folder"))

export function UI(){
    return <screengui>
        <frame 
            Position={new UDim2(0.385, 0, 0.314, 0)} 
            Size={new UDim2(0.23, 0, 0.371, 0)}
            BackgroundColor3={new Color3(31, 31, 31)}
        >

        </frame>
    </screengui>
}

root.render(<StrictMode>{createPortal(<UI/>, gui)}</StrictMode>)
```

# Error

```
D:\Rojo\TS\ProduceGnarpsAndFight>yarn watch
yarn run v1.22.19
$ rbxtsc -w
[5:53:39 PM] Starting compilation in watch mode...

[5:53:41 PM] Found 0 errors. Watching for file changes.

[5:54:47 PM] File change detected. Starting incremental compilation...

D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:169
                throw e;
                ^

Error: Assertion Failed!
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformJsxTagNameExpression (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:19:33)
    at D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:40:55
    at D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:60
    at TransformState.capturePrereqs (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:128:9)
    at TransformState.capture (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:30)
    at transformJsxTagName (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsxTagName.js:40:41)
    at transformJsx (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\nodes\jsx\transformJsx.js:27:84)
    at transformJsxElement (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformJsxElement.js:6:44)
    at transformExpression (D:\Rojo\TS\ProduceGnarpsAndFight\node_modules\roblox-ts\out\TSTransformer\nodes\expressions\transformExpression.js:98:16)

Node.js v20.11.1
```

**Comment by OverHash** [comment]
What is your `tsconfig.json`? I am confused how you are importing `Roact` when `@rbxts/react` does not export this.

**Comment by Dionysusnu** [comment]
Just out of curiosity, what's the template you used?

Check the [readme](https://www.npmjs.com/package/@rbxts/react#-troubleshooting) for React (*which is not the same as Roact), and try the steps in the section for `jsxFactory`.

**Comment by doqedev** [comment]
sorry for the VERY VERY late reply,
the template I used is the rbxts game template (yarn create roblox-ts game)
## My TSConfig.json
```json
{
  "compilerOptions": {
    // required
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "jsx": "react",
    "jsxFactory": "Roact.createElement",
    "jsxFragmentFactory": "Roact.createFragment",
    "module": "commonjs",
    "moduleResolution": "Node",
    "noLib": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "moduleDetection": "force",
    "strict": true,
    "target": "ESNext",
    "typeRoots": ["node_modules/@rbxts", "node_modules/@flamework"],
    "plugins": [{ "transform": "rbxts-transformer-flamework" }],

    // configurable
    "rootDir": "src",
    "outDir": "out",
    "baseUrl": "src",
    "incremental": true,
    "tsBuildInfoFile": "out/tsconfig.tsbuildinfo"
  }
}
```

**Comment by OverHash** [comment]
As per the README of the [`@rbxts/react`](https://www.npmjs.com/package/@rbxts/react) package, you must set your `tsconfig.json` to have:
```json
"compilerOptions": {
  "jsxFactory": "React.createElement",
  "jsxFragmentFactory": "React.Fragment"
}
```
