### ISSUE TITLE
Property decorator compiler assertion

### ISSUE THREAD

**Issue by cmumme** [roblox-ts/roblox-ts#2756]
Windows 11 23H2
roblox-ts@next

The current version of ``roblox-ts@next`` (7/24/2024) results in a compiler assertion failure whenever I use property decorators. This is noted by @paradoxuum to be caused by the change in transformMethodDeclaration introduced by #2460.

Sample code:
```ts
export function Replicated(target: object, propertyKey: string | symbol) {
    return Reflect.metadata(REPLICATED_METADATA_KEY, true)(target, propertyKey)
}

export default class Components {
    @Replicated
    public static readonly Time = component<{
        isDaytime: boolean,
        secondsElapsed: number,
        daysPassedSinceStart: number,
        nightsPassedSinceStart: number
    }>("Time", {
        isDaytime: true,
        secondsElapsed: 0,
        daysPassedSinceStart: 0,
        nightsPassedSinceStart: 0
    })
}
```

Assertion stack trace:
```
    at assert (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at transformMemberDecorators (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformDecorators.js:34:33)
    at transformPropertyDecorators (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformDecorators.js:78:12)
    at transformDecorators (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformDecorators.js:116:58)
    at transformClassLikeDeclaration (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\class\transformClassLikeDeclaration.js:252:101)
    at transformClassDeclaration (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformClassDeclaration.js:6:78)
    at transformStatement (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformStatement.js:76:16)
    at c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:27:123
    at c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:132:60
    at TransformState.capturePrereqs (c:\Users\camre.VIRT-MACHINE\OneDrive\Documents\Shared\Projects\2024\Roblox\cmumme\IKEAv2\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:127:9)
```

**Comment by Dionysusnu** [comment]
#2460 only changed the way this occurs - previously, this bug duplicated the property key when calling the decorator.
