### ISSUE TITLE
Error: Assertion Failed! ForOf iteration type not implemented: any

### ISSUE THREAD

**Issue by sdxqw** [roblox-ts/roblox-ts#2840]
[4:54:47 PM] Starting compilation in watch mode...

c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\Project\functions\setupProjectWatchProgram.js:172
                throw e;
                ^

Error: Assertion Failed! ForOf iteration type not implemented: any
This is a compiler bug! Please submit a bug report here:
https://github.com/roblox-ts/roblox-ts/issues
    at assert (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\Shared\util\assert.js:7:15)
    at getLoopBuilder (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:330:29)
    at transformForOfStatement (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformForOfStatement.js:377:25)
    at transformStatement (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformStatement.js:79:16)
    at c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:27:123
    at c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:60
    at TransformState.capturePrereqs (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:128:9)
    at TransformState.capture (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\classes\TransformState.js:133:30)
    at transformStatementList (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\nodes\transformStatementList.js:27:65)
    at transformFunctionDeclaration (c:\Roblox\Dev\WhatsNewPS\node_modules\roblox-ts\out\TSTransformer\nodes\statements\transformFunctionDeclaration.js:28:102)

Node.js v20.18.0
Compiler exited with code 1

**Comment by plasma-node** [comment]
Also experiencing this exact bug
