### ISSUE TITLE
OpenBraceToken was not found

### ISSUE THREAD

**Issue by bohdan77** [roblox-ts/roblox-ts#554]
```typescript
interface ComponentRegistry {}

interface ISystem {}

export class ServerCharacterInputSystem implements ISystem {
    Initialize(registry: ComponentRegistry): void {}
}
```
Causes the compiler to crash in watch mode.
After activating watch mode, add a ">" at the end of "ServerCharacterInputSystem",
and after it compiles delete it.
This is the smallest repro where I could get it to work consistently, sometimes it doesn't at all. This looks like a ts-morph error?
On version 0.2.9

stack trace:
```
(node:11256) UnhandledPromiseRejectionWarning: Error: Unexpected scenario where a(n) OpenBraceToken was not found.
-- Details --
Path: C:/Users/zobki/Projects/novocaine/src/shared/Network/Clock/test.ts
Text: "interface ComponentRegistry {}\n\ninterface ISystem {}\n\nexport class ServerCharacterInputSystem implements ISystem {\n    Initialize(registry: ComponentRegistry): void {}\n}\n"
Stack: Error: Unexpected scenario where a(n) OpenBraceToken was not found.
    at getTokenEnd (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:87:23)
    at Function.getContainerBodyPos (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:78:20)
    at getNodes (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:98:48)
    at getNodes.next (<anonymous>)
    at Function.from (<anonymous>)
    at Function.getOrParseChildren (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\utils\CommentNodeParser.js:37:30)
    at Function.getCompilerForEachChildren (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\utils\ExtendedParser.js:26:79)
    at ClassDeclaration._getCompilerForEachChildren (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\common\Node.js:1303:39)
    at ClassDeclaration._getCompilerChildrenFast (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\common\Node.js:1310:96)
    at ClassDeclaration._getChildrenInCacheIterator (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\common\Node.js:347:31)
    at Object.doManipulation (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\manipulation\manipulations\doManipulation.js:12:15)
    at Object.insertIntoParentTextRange (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\manipulation\manipulations\insertion.js:15:22)
    at SourceFile.replaceText (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\base\TextInsertableNode.js:27:28)
    at SourceFile._refreshFromFileSystemInternal (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\module\SourceFile.js:746:14)
    at SourceFile.<anonymous> (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\module\SourceFile.js:589:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\zobki\AppData\Roaming\npm\node_modules\roblox-ts\node_modules\ts-morph\dist\compiler\ast\module\SourceFile.js:10:58)
(node:11256) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11256) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by osyrisrblx** [comment]
Super weird. I'll see if I can make a self contained ts-morph repro with this and report it.
